-- =========================================================================
-- asnvil Test Vector: 1002_named_numbers.asn1
-- Description: INTEGER named numbers with identifier references
-- Attribution: Adapted from vlm/asn1c project (MIT license)
--              https://github.com/vlm/asn1c
-- =========================================================================

TestModule DEFINITIONS AUTOMATIC TAGS ::= BEGIN
    MyInt ::= INTEGER { foo( Bar ), baz( 2 ) }
    NextType ::= BOOLEAN
END;
